### ISSUE TITLE
Customizing the font of NativeMarkText

### ISSUE THREAD

**Issue by flixlo** [andyfinnell/NativeMarkKit#10] opened 2021-07-09 16:35 UTC
Hi!

I am trying to customize the font of `NativeMarkText` and I want to set `Avenir-Medium` as the default font. Unfortunately, the view does not display the correct font. That's why I tested different fonts from the `Avenir` font family and described my findings below.

## Test Cases
Please see below for the actual code I used to generate the following example. The first line displays the text with a default `Text`-View and the respective font. The second line displays the text with the `NativeMarkText`-View and the respective font.

As you can see in the screenshot, using the fonts `Avenir-Book` and `Avenir-Heavy` seems to be working - both lines look exactly the same. 

With the fonts `Avenir-Roman` and `Avenir-Medium`, you can see slight differences (compare the width and weight) between the `NativeMarkText`-View and the default `Text`-View. It looks like in both cases the font `Avenir-Book` is used instead of `Roman/Medium`.

Am I doing something wrong, or is it not possible to specify e.g. `Avenir-Medium` as the base font for the markdown text view?

<img src="https://user-images.githubusercontent.com/12484787/125108228-11280c00-e0e2-11eb-81ec-7437dba410d5.png" width=400/>

## Test-Code
```swift
import SwiftUI
import NativeMarkKit

struct TestNativeMarkKitView: View {

    private let fontSize: CGFloat = 19.0
    private let backgroundColor: Double = 0.9

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            createTextViews(fontName: "Avenir-Book")
            createTextViews(fontName: "Avenir-Roman")
            createTextViews(fontName: "Avenir-Medium")
            createTextViews(fontName: "Avenir-Heavy")
        }
        .padding(20)
    }

    private func createTextViews(fontName: String) -> some View {
        VStack(alignment: .leading, spacing: 1) {
            Text("\(fontName)")
                .font(.custom("Times New Roman", size: 12))

            // Default text
            HStack(spacing: 5) {
                Text("Avenir Avenir Avenir Avenir")
                    .font(.custom(fontName, size: fontSize))
                    .background(Color(red: backgroundColor, green: backgroundColor, blue: backgroundColor, opacity: 1.0))

                Text("(Default)")
                    .font(.custom("Times New Roman", size: 8))
            }

            // NativeMarkKit text
            HStack(spacing: 5) {
                NativeMarkText("Avenir Avenir Avenir Avenir", styleSheet: createStyleSheet(fontName: fontName))

                Text("(NativeMark)")
                    .font(.custom("Times New Roman", size: 8))
            }
        }
    }

    private func createStyleSheet(fontName: String) -> StyleSheet {
        return StyleSheet.default.duplicate().mutate(
            block: [
                .document: [
                    .textStyle(.custom(name: .custom(fontName), size: .fixed(fontSize))),
                    .backgroundColor(UIColor(red: CGFloat(backgroundColor), green: CGFloat(backgroundColor), blue: CGFloat(backgroundColor), alpha: 1.0))
                ]
            ]
        )
    }
}
```

Thx for your help!

**Comment by andyfinnell** [comment] 2021-07-09 21:23
Thanks for the bug report! The sample code was very helpful. With it, I'm able to reproduce it on both iOS and macOS. I'll start investigating the cause this evening.

**Comment by andyfinnell** [comment] 2021-07-09 23:05
@flixlo I got a fix in `master` now, and tagged it as `2.0.1`. Let me know if you're still having issues.

**Comment by flixlo** [comment] 2021-07-12 14:38
@andyfinnell Thank you for your quick response and the new release! 👍 

It seems that `italic` text still uses `Avenir-Book` instead of `Avenir-Medium`. I used the following code to test different scenarios for bold and italic text.

<img width="201" alt="grafik" src="https://user-images.githubusercontent.com/12484787/125305631-c8b15e00-e32e-11eb-99a2-4257cc6fb22d.png">

```swift
NativeMarkText("normal", styleSheet: createStyleSheet(fontName: fontName))
NativeMarkText("*italic*", styleSheet: createStyleSheet(fontName: fontName))
NativeMarkText("**bold**", styleSheet: createStyleSheet(fontName: fontName))
NativeMarkText("***bold & italic***", styleSheet: createStyleSheet(fontName: fontName))
NativeMarkText("**bold / *bold & italic***", styleSheet: createStyleSheet(fontName: fontName))
NativeMarkText("*italic / **italic & bold***", styleSheet: createStyleSheet(fontName: fontName))
```

**Comment by andyfinnell** [comment] 2021-07-12 22:19
:oof: It seems like the API Apple is providing to specify italic/bold isn't that smart. AppKit has `NSFontManager`, which contains an old API that appears to do the right thing and fix this bug. But UIKit has no counterpart to `NSFontManager`. I'll see what can be done on iOS; it will probably take a while to figure out.

**Comment by andyfinnell** [comment] 2021-07-13 23:08
@flixlo I've put up a potential fix in #12  (branch `bugs/custom-font-italic-does-not-preserve-weight-10`). If you want to point to that branch and see if that fixes things, I'd appreciate it.

**Comment by flixlo** [comment] 2021-07-14 13:30
@andyfinnell Thank you again for the quick response! I did some testing on the branch and the italic text styling works properly now. Unfortunately, combining italic and bold text does not work anymore. 

## Branch: bugs/custom-font-italic-does-not-preserve-weight-10
- 1, 2, 3 work properly
- 4, 5, 6 dont work
<img width="284" alt="grafik" src="https://user-images.githubusercontent.com/12484787/125629555-ce26e5a7-2d13-4ee2-a396-fcb16a50ee3c.png">

## Version: 2.0.1
- 1, 3, 4, 5 work properly
- 2, 6 dont work
<img width="284" alt="grafik" src="https://user-images.githubusercontent.com/12484787/125629592-29d414ab-11b2-4264-9c03-419a7d903c89.png">

## Version: 2.0.0
<img width="284" alt="grafik" src="https://user-images.githubusercontent.com/12484787/125629617-e8396c15-96f4-447f-bd5c-6229fb3ee20a.png">

## Markdown Text
```swift
NativeMarkText("1 -- normal", styleSheet: createStyleSheet(fontName: fontName))
NativeMarkText("2 -- *italic*", styleSheet: createStyleSheet(fontName: fontName))
NativeMarkText("3 -- **bold**", styleSheet: createStyleSheet(fontName: fontName))
NativeMarkText("4 -- ***bold & italic***", styleSheet: createStyleSheet(fontName: fontName))
NativeMarkText("5 -- **bold -- *bold & italic***", styleSheet: createStyleSheet(fontName: fontName))
NativeMarkText("6 -- *italic -- **italic & bold***", styleSheet: createStyleSheet(fontName: fontName))
```

## Full test code
```swift
import SwiftUI
import NativeMarkKit

struct TestNativeMarkKitView: View {

    private let fontSize: CGFloat = 19.0
    private let backgroundColor: Double = 0.9

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            //createTextViews(fontName: "Avenir-Book")
            //createTextViews(fontName: "Avenir-Roman")
            createTextViews(fontName: "Avenir-Medium")
            //createTextViews(fontName: "Avenir-Heavy")
        }
        .padding(20)
    }

    private func createTextViews(fontName: String) -> some View {
        VStack(alignment: .leading, spacing: 1) {
            Text("\(fontName)")
                .font(.custom("Times New Roman", size: 12))

            NativeMarkText("1 -- normal", styleSheet: createStyleSheet(fontName: fontName))
            NativeMarkText("2 -- *italic*", styleSheet: createStyleSheet(fontName: fontName))
            NativeMarkText("3 -- **bold**", styleSheet: createStyleSheet(fontName: fontName))
            NativeMarkText("4 -- ***bold & italic***", styleSheet: createStyleSheet(fontName: fontName))
            NativeMarkText("5 -- **bold -- *bold & italic***", styleSheet: createStyleSheet(fontName: fontName))
            NativeMarkText("6 -- *italic -- **italic & bold***", styleSheet: createStyleSheet(fontName: fontName))
        }
    }

    private func createStyleSheet(fontName: String) -> StyleSheet {
        return StyleSheet.default.duplicate().mutate(
            block: [
                .document: [
                    .textStyle(.custom(name: .custom(fontName), size: .fixed(fontSize))),
                    .backgroundColor(UIColor(red: CGFloat(backgroundColor), green: CGFloat(backgroundColor), blue: CGFloat(backgroundColor), alpha: 1.0))
                ]
            ]
        )
    }
}
```

**Comment by andyfinnell** [comment] 2021-07-14 22:04
Sorry about the regression, I've pushed a fix. Here's the current rendering of your test case on the `bugs/custom-font-italic-does-not-preserve-weight-10` branch:

https://github.com/andyfinnell/NativeMarkKit/blob/976f17357cf0e5402a0deef5c5b013b2d4a777f2/Tests/NativeMarkKitTests/Fixtures/CustomFontsWithBoldAndItalic.iOS.png

Let me know if things look correct to you.

**Comment by flixlo** [comment] 2021-07-14 22:27
@andyfinnell Thx for your effort, it works now 👍

**Closed** 2021-07-15 11:03 UTC
